AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  restoredatabasecopyforverification:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::215291861542:role/service-role/verify-database-copy'
      Environment:
        Variables:
          DB_PORT: '3306'
          DB_ENGINE: mysql
          DB_LICENSE_MODEL: general-public-license
          DB_SUBNET_GROUP_NAME: default
          DB_SNAPSHOT_IDENTIFIER_PREFIX: production
          DB_AVAILABILITY_ZONE: us-east-1f
          DB_INSTANCE_CLASS: db.t2.medium
          DB_INSTANCE_IDENTIFIER: verification-copy
          DB_OPTION_GROUP_NAME: 'default:mysql-5-6'
          DB_STORAGE_TYPE: gp2
