kind: pipeline
name: default

clone:
  disable: true

steps:
steps:
- name: clone
  image: docker:git
  commands:
  - git clone --depth=50 --branch=$DRONE_BRANCH $DRONE_REPO_LINK
  - cd $DRONE_REPO_NAME
  - git checkout $DRONE_COMMIT

- name: testing
  image: wintercdo/code-dot-org:0.7
  when:
    branch:
    - drone
  environment:
    CLOUDFRONT_KEY_PAIR_ID:
      from_secret: CLOUDFRONT_KEY_PAIR_ID
    CLOUDFRONT_PRIVATE_KEY:
      from_secret: CLOUDFRONT_PRIVATE_KEY
    PROPERTIES_ENCRYPTION_KEY:
      from_secret: PROPERTIES_ENCRYPTION_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - pwd
    - whoami
    - id -u
    - id -g
    - ls -alh
    - sudo chown -R circleci:circleci .
    - /entrypoint.sh docker/unit_tests.sh
