kind: pipeline
name: default

clone:
  depth: 1

steps:
- name: testing
  image: wintercdo/code-dot-org:0.7
  when:
    branch:
    - drone
  environment:
    CLOUDFRONT_KEY_PAIR_ID:
      from_secret: CLOUDFRONT_KEY_PAIR_ID
    CLOUDFRONT_PRIVATE_KEY:
      from_secret: CLOUDFRONT_PRIVATE_KEY
    PROPERTIES_ENCRYPTION_KEY:
      from_secret: PROPERTIES_ENCRYPTION_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
#  volumes:
#  - name: mysql
#    path: /var/lib/mysql
#  - name: rbenv
#    path: /home/circleci/.rbenv
#  - name: yarncache
#    path: /home/circleci/.cache
  commands:
    - pwd
    - whoami
    - id -u
    - id -g
    - ls -alh
    - sudo chown -R circleci:circleci .
    - /entrypoint.sh docker/unit_tests.sh

#volumes:
#- name: mysql
#  temp: {}
#- name: rbenv
#  temp: {}
#- name: yarncache
#  temp: {}