inherit_from:
  - .rubocop_hound.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'apps/**/*'
    - 'dashboard/db/schema.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.2

# BEGIN CODE.ORG OVERRIDES

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/NumericLiterals:
  MinDigits: 7

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/WordArray:
  MinSize: 5

# END CODE.ORG OVERRIDES

# BEGIN BLACKLIST

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# As of July 2016, there is enough disagreement in our codebase, on our team,
# and apathy to the rule to suggest a negative cost-benefit of enabling the
# rule.
Style/StringLiterals:
  Enabled: false

# END BLACKLIST
