# Several new cops were added to RuboCop bewteen 0.52
# and 1.28. RuboCop wants us to explicitly enable or
# disable every rule, so here we disable all new rules
# until we can selectively add them.

Gemspec/DateAssignment: # new in 1.10
  Enabled: false
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: false
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: false
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/DeprecatedConstants: # new in 1.8
  Enabled: false
Lint/DuplicateBranch: # new in 1.3
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: false
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: false
Lint/RefinementImportMethods: # new in 1.27
  Enabled: false
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
Lint/ToEnumArguments: # new in 1.1
  Enabled: false
Lint/TripleQuotes: # new in 1.9
  Enabled: false
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: false
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: false
Naming/BlockForwarding: # new in 1.24
  Enabled: false
Security/CompoundHash: # new in 1.28
  Enabled: false
Security/IoMethods: # new in 1.22
  Enabled: false
Style/ArgumentsForwarding: # new in 1.1
  Enabled: false
Style/CollectionCompact: # new in 1.2
  Enabled: false
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: false
Style/EndlessMethod: # new in 1.8
  Enabled: false
Style/FetchEnvVar: # new in 1.28
  Enabled: false
Style/FileRead: # new in 1.24
  Enabled: false
Style/FileWrite: # new in 1.24
  Enabled: false
Style/HashConversion: # new in 1.10
  Enabled: false
Style/HashExcept: # new in 1.7
  Enabled: false
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: false
Style/InPatternThen: # new in 1.16
  Enabled: false
Style/MapToHash: # new in 1.24
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: false
Style/NestedFileDirname: # new in 1.26
  Enabled: false
Style/NilLambda: # new in 1.3
  Enabled: false
Style/NumberedParameters: # new in 1.22
  Enabled: false
Style/NumberedParametersLimit: # new in 1.22
  Enabled: false
Style/ObjectThen: # new in 1.28
  Enabled: false
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantArgument: # new in 1.4
  Enabled: false
Style/RedundantInitialize: # new in 1.27
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Style/SwapValues: # new in 1.1
  Enabled: false
Performance/AncestorsInclude: # new in 1.7
  Enabled: false
Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: false
Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: false
Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: false
Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: false
Performance/ConstantRegexp: # new in 1.9
  Enabled: false
Performance/MapCompact: # new in 1.11
  Enabled: false
Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: false
Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: false
Performance/RedundantSortBlock: # new in 1.7
  Enabled: false
Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: false
Performance/RedundantStringChars: # new in 1.7
  Enabled: false
Performance/ReverseFirst: # new in 1.7
  Enabled: false
Performance/SortReverse: # new in 1.7
  Enabled: false
Performance/Squeeze: # new in 1.7
  Enabled: false
Performance/StringIdentifierArgument: # new in 1.13
  Enabled: false
Performance/StringInclude: # new in 1.7
  Enabled: false
Performance/Sum: # new in 1.8
  Enabled: false
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: false
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: false
Rails/AddColumnIndex: # new in 2.11
  Enabled: false
Rails/AfterCommitOverride: # new in 2.8
  Enabled: false
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: false
Rails/CompactBlank: # new in 2.13
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: false
Rails/DuplicateAssociation: # new in 2.14
  Enabled: false
Rails/DuplicateScope: # new in 2.14
  Enabled: false
Rails/DurationArithmetic: # new in 2.13
  Enabled: false
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: false
Rails/ExpandedDateRange: # new in 2.11
  Enabled: false
Rails/FindById: # new in 2.7
  Enabled: false
Rails/I18nLazyLookup: # new in 2.14
  Enabled: false
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: false
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false
Rails/Inquiry: # new in 2.7
  Enabled: false
Rails/MailerName: # new in 2.7
  Enabled: false
Rails/MatchRoute: # new in 2.7
  Enabled: false
Rails/MigrationClassName: # new in 2.14
  Enabled: false
Rails/NegateInclude: # new in 2.7
  Enabled: false
Rails/Pluck: # new in 2.7
  Enabled: false
Rails/PluckInWhere: # new in 2.7
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: false
Rails/RedundantTravelBack: # new in 2.12
  Enabled: false
Rails/RenderInline: # new in 2.7
  Enabled: false
Rails/RenderPlainText: # new in 2.7
  Enabled: false
Rails/RootJoinChain: # new in 2.13
  Enabled: false
Rails/ShortI18n: # new in 2.7
  Enabled: false
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: false
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: false
Rails/TransactionExitStatement: # new in 2.14
  Enabled: false
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: false
Rails/WhereEquals: # new in 2.9
  Enabled: false
Rails/WhereExists: # new in 2.7
  Enabled: false
Rails/WhereNot: # new in 2.8
  Enabled: false
