inherit_from: .rubocop_hound.yml
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'apps/**/*'
    - 'dashboard/scripts/**/*'
  RunRailsCops: true
  DisplayCopNames: true

# Listed are rules we don't plan to enable in the foreseeable future.
# Add rules we plan to fix (but are currently failing) to .rubocop_todo.yml.

Style/BarePercentLiterals:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false
