scss_files: 'dashboard/app/**/*.css.scss'

linters:
  QualifyingElement:
    allow_element_with_attribute: true
    allow_element_with_class: true
  Shorthand:
    allowed_shorthands: [1, 2, 4]

  # Rules we should either ignore or fix (but are currently failing).
  BorderZero:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  DeclarationOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerProperty:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: false
