git:
  depth: 10
language: ruby

rvm: 2.0.0

sudo: false

cache: bundler

gemfile: Gemfile

bundler_args: --without development --deployment

before_script: bundle exec rake install; cd dashboard

script: bundle exec rake

env:
  global:
  - DB=mysql
  - RAILS_ENV=test
