---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[cdo-ruby]
  - name: new
    run_list:
      - recipe[apt]
      - recipe[cdo-ruby]
    attributes:
      cdo-ruby:
        version: '2.2'
        bundler_version: '1.10.6'
  - name: upgrade
    run_list:
      - recipe[apt]
      - recipe[cdo-ruby::2.0]
      - recipe[cdo-ruby]
    attributes:
      cdo-ruby:
        version: '2.2'
        bundler_version: '1.10.6'
