AWSTemplateFormatVersion: '2010-09-09'
Description: 'prune-aurora-backups

  Sample SAM Template for prune-aurora-backups

  '
Globals:
  Function:
    Timeout: 3
Resources:
  OncePerDayRule:
    Properties:
      Description: Run prune aurora backups once per day.
      Name:
        Fn::Sub: ${AWS::StackName}-OncePerDay
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - PruneAuroraBackupsFunction
          - Arn
        Id: PruneAuroraBackupsFunctionTarget
    Type: AWS::Events::Rule
  PermissionForEventsToInvokeLambda:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PruneAuroraBackupsFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - OncePerDayRule
        - Arn
    Type: AWS::Lambda::Permission
  PruneAuroraBackupsFunction:
    Properties:
      CodeUri: s3://cdo-devo-sam/2bd2a4e43b2fe681eb878f011de1a440
      Handler: prune-aurora-backups.handler
      Role:
        Fn::GetAtt:
        - PruneAuroraBackupsRole
        - Arn
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  PruneAuroraBackupsRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonRDSFullAccess
      RoleName: PruneAuroraBackupsRole
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
