---
driver:
  name: dokken
  chef_version: 12.7.2

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
  attributes:
    cdo-apps:
      dashboard:
        port: 8080
      pegasus:
        port: 8081
      i18n:
        languages:
          en: English
          fr: French
  run_list:
  - recipe[apt]

verifier:
  root_path: '/opt/verifier'

suites:
  - name: default
    run_list:
      - recipe[varnish_test]
#      - recipe[minitest-handler]
  - name: cloudfront
    run_list:
      - recipe[varnish_test]
      - recipe[varnish_test::ngrok]
    attributes:
      varnish_test:
        authtoken: <%= ENV['NGROK_TOKEN'] %>
