---
driver:
  name: dokken
#  chef_version: 12.7.2
  chef_version: latest
#  chef_version: 15.2
#  chef_version: 14.12.3
  cap_add:
  # needed for setting hostname
    - SYS_ADMIN
  privileged: true # because Docker and SystemD/Upstart


transport:
  name: dokken
provisioner:
  name: dokken
  chef_license: accept
  log_level: info
platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
    attributes:
      cdo-repository:
        branch: <%= `git rev-parse --abbrev-ref HEAD` %>
    run_list:
      - recipe[cdo-apps]
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
    attributes:
      cdo-repository:
        branch: <%= `git rev-parse --abbrev-ref HEAD` %>
    run_list:
      - recipe[cdo-apps]
suites:
  - name: default
  - name: daemon
    attributes:
      cdo-apps:
        daemon: true
  - name: stop
    run_list:
      - recipe[cdo-apps]
      - recipe[cdo-apps::stop]
