AWSTemplateFormatVersion: 2010-09-09
Description: 'S3 Buckets'
Resources:
  ## Create S3 bucket for student libraries
  LibraryBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cdo-v3-libraries'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: 'Enabled'
      LoggingConfiguration:
        DestinationBucketName: 'cdo-logs'
        LogFilePrefix: 's3/cdo-v3-libraries'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SpritelabAnimationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cdo-spritelab-animation-library'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: 'Enabled'
      LoggingConfiguration:
        DestinationBucketName: 'cdo-logs'
        LogFilePrefix: 's3/cdo-spritelab-animation-library'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # for curriculumbuilder
  CurriculumBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cdo-curriculum-devel'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: 'Enabled'
      LoggingConfiguration:
        DestinationBucketName: 'cdo-logs'
        LogFilePrefix: 's3/cdo-curriculum-devel'
      PolicyDocument: {
        "Version": "2008-10-17",
        "Statement": [
            {
                "Sid": "PublicReadForGetBucketObjects",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::cdo-curriculum-devel/*"
            },
            {
                "Sid": "",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "arn:aws:iam::475661607190:user/josh@code.org"
                },
                "Action": "s3:*",
                "Resource": [
                    "arn:aws:s3:::cdo-curriculum-devel/*",
                    "arn:aws:s3:::cdo-curriculum-devel"
                ]
            }
        ]
      }
