# Note that due to a limitation in the Docker AUFS driver,
# this cookbook's integration test will not run correctly within a Docker container.
#
# To run tests using EC2 configuration instead of Docker, run:
# KITCHEN_LOCAL_YAML=../.kitchen.ec2.yml bundle exec kitchen verify
---
transport:
  name: sftp
driver:
  name: docker
  use_sudo: false
  privileged: true
provisioner:
  name: chef_zero
  require_chef_omnibus: 15.2.20
platforms:
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[cdo-freegeoip]
